# Generated by Django 4.1.7 on 2023-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='create_time',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
