# Generated by Django 4.1.7 on 2023-03-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_employees_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
