# Generated by Django 4.1.7 on 2023-03-18 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_employees_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='create_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
    ]
