# Generated by Django 4.1.7 on 2023-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_employees_create_time_alter_employees_depart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('Funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投资')),
                ('level', models.SmallIntegerField(choices=[(1, '普通'), (2, '高级'), (3, '顶级')], verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '进行中'), (2, '已交付')], verbose_name='状态')),
            ],
        ),
    ]
